#Sample docker compose file for the dockjob image.
# this shows how to run dockjob using kong to make it https
#  dock job itself isn't exposed, instead kong is exposed and passes requests to dockjob
#
#note: it is recommended you change :latest to a specific version number

version: "3.1"

secrets:
  webservices_cert:
    external: true
  webservices_key:
    external: true

services:
  kong-database:
    image: postgres:9.6
    deploy:
      restart_policy:
        condition: any
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong:0.13
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations up
    deploy:
      restart_policy:
        condition: on-failure

  kong:
    #tried changing to kong:0.12.0-alpine but didn't work as health check needs curl
    image: kong:0.13
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
     - webservices_cert
     - webservices_key
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_SSL_CERT=/run/secrets/webservices_cert
      - KONG_SSL_CERT_KEY=/run/secrets/webservices_key
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - 443:8443
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10

  dockjob:
    image: metcarob/dockjob:latest
    environment:
      - APIAPP_APIURL=${EXTURL}:${EXTPORT}/dockjobapi
      - APIAPP_APIDOCSURL=${EXTURL}:${EXTPORT}/dockjobapidocs
      - APIAPP_FRONTENDURL=${EXTURL}:${EXTPORT}/dockjob
    deploy:
      restart_policy:
        condition: any

  #Add API's to kong to forward requests to dockjob
  kong-addapis-dockjob:
    image: metcarob/docker-ws-caller:0.0.9
    deploy:
      restart_policy:
        condition: on-failure
        delay: 6s
    entrypoint: "/bin/sh"
    command:    "-c \" \
                   (kong_install_service_and_route http://kong:8001 dockjobapi http dockjob 80 \\\"/api\\\" https /dockjobapi) && \
                   (kong_install_service_and_route http://kong:8001 dockjobapidocs http dockjob 80 \\\"/apidocs\\\" https /dockjobapidocs) && \
                   (kong_install_service_and_route http://kong:8001 dockjob http dockjob 80 \\\"/frontend\\\" https /dockjob) \
               \""

##The next section starts a UI for kong called konga. 
##We only need a ui for development experimentation and can be removed if no UI is required
## when it is running it can be accessed on port 1337
#  konga:
#    image: pantsel/konga
#    deploy:
#      restart_policy:
#        condition: on-failure
#    ports:
#     - 1337:1337


## docker stack deploy --compose-file=docker-compose-https.yml dockjob-https
